spring.application.name=gateway

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[1].id=vendas
spring.cloud.gateway.routes[1].uri=lb://vendas-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/vendas/**

server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=health
