spring.application.name=vendas-service
server.port=8082
spring.config.import=optional:configserver:http://localhost:8888
spring.r2dbc.url=r2dbc:postgresql://${VENDAS_DB_HOST:localhost}:5432/vendasdb
spring.r2dbc.username=vendas
spring.r2dbc.password=${VENDAS_DB_PASSWORD}
spring.sql.init.mode=always
produtos.base-url=${PRODUTOS_BASE_URL:http://localhost:8081}
management.endpoints.web.exposure.include=health
